### ISSUE TITLE
Constructor doesn't respect provided base URL

### ISSUE THREAD

**Issue by vicmosin** [jsor/hal-client#1]
Client defined like this:

```
$this->client = new HalClient('http://www.example.com/bla/bla2/bla3');
```

will make all of the requests to `http://www.example.com`.

Bug or feature?

**Comment by jsor** [comment]
The URL assembling is done by [`Guzzle\Psr7\Uri::resolve`](https://github.com/guzzle/psr7/blob/master/src/Uri.php#L112-L184).

This means, it depends how you define the root URL and the request URI's, especially how you include trailing slashes in the root URL and leading slashes in the request URI's.

I've added a [test](https://github.com/jsor/hal-client/blob/master/tests/HalClientTest.php#L22-L100) where you can see how assembling behaves in 36a56860909699b716c81162722b4972076d5096.

I'd always define the root URL with a trailing slash like: `http://www.example.com/bla/bla2/bla3/`.

Then `$client->get('test')` resolves to `http://www.example.com/bla/bla2/bla3/test` and  `$client->get('/test')` (note the leading slash) resolves to  `http://www.example.com/test`.
